# Generated by Django 3.1 on 2020-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps4game',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ps4game',
            name='gptime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ps4game',
            name='metacritic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ps4game',
            name='release',
            field=models.IntegerField(default=0),
        ),
    ]
