# Generated by Django 3.1 on 2020-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4games', '0002_auto_20200821_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps4game',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
