# Generated by Django 3.1 on 2020-08-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps4games', '0003_ps4game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ps4game',
            name='image',
            field=models.FileField(default=0, upload_to=''),
        ),
    ]
